DROP TABLE IF EXISTS patients CASCADE;

CREATE TABLE patients(
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    age INTEGER NOT NULL,
    disease VARCHAR(255) NOT NULL
);